### ISSUE TITLE
Mac excecutable and dependencies

### ISSUE THREAD

**Issue by Wano-k** [RPG-Paper-Maker/RPG-Paper-Maker#1]
We need the help of someone having mac OSX to make the engine available for this platform. First, you should build the project on a mac OSX machine (see README.md). Open the game.pro with QtCreator and build it in release mode if all is already OK in debug mode. Go get the `Game.app` generated in the released build and put it in `Engine/Content/mac` folder.

After that, create a new project, go to its folder and try to launch the app from here. This should not work (if it is, you should try to hide Qt by any way, like temporary renaming the Qt installation folder). We need this app to work for any user from mac that don't have Qt installed. You should check what are the dependencies for mac to deploy the app in standalone. Once you figure it out, put all the stuff needed in the folder `Engine/Content/mac`.

Do the same thing  with release build of `engine.pro` and put the dependencies in a folder `Engine/Dependencies/mac`.

**Comment by afaur** [comment]
Build succeeds for both `engine` and `game` however the `engine` errors when creating a new project.
<img width="464" alt="engine-one" src="https://user-images.githubusercontent.com/898523/27997694-da7daf0c-64b2-11e7-93f2-01b3b60aa34c.png">

<img width="454" alt="engine-two" src="https://user-images.githubusercontent.com/898523/27997696-e1dfdcf2-64b2-11e7-866e-f962e521c67b.png">

<img width="1440" alt="engine-three" src="https://user-images.githubusercontent.com/898523/27997698-e6144588-64b2-11e7-9eab-ef33a12b427d.png">

<img width="533" alt="engine-four" src="https://user-images.githubusercontent.com/898523/27997699-ed1d5fd6-64b2-11e7-9b6b-aa1d57f02e74.png">

<img width="706" alt="engine-five" src="https://user-images.githubusercontent.com/898523/27997701-f2978752-64b2-11e7-8d35-cc0219c6b8d8.png">

<img width="422" alt="engine-six" src="https://user-images.githubusercontent.com/898523/27997702-f7915ef4-64b2-11e7-85a7-5fbc92555ad7.png">

<img width="342" alt="game-one" src="https://user-images.githubusercontent.com/898523/27997703-fbceb746-64b2-11e7-94a5-401cc3476826.png">

<img width="641" alt="game-two" src="https://user-images.githubusercontent.com/898523/27997704-ff70f6a2-64b2-11e7-96e0-9a39be240959.png">

**Comment by Wano-k** [comment]
Thanks a lot! 

Hmm that's weird when you are creating the project, there is no text field for the location? There should be one. Is there at least a project directory created in the location specified after the error? Also, could you please show me the `Content` folder in your build engine folder, there might be something missing (there should be a `build...Release/Content/basic/Content` folder.

For the game, I would like to see the `Content` folder too, you should have a `build...Release/Content/Datas/Scripts` folder.

**Comment by afaur** [comment]
_Is there at least a project directory created in the location specified after the error?_ 
Yes, a folder gets created however only one file is made inside of the folder.
```sh
[RPG Paper Maker Games/Projects/testproj]
-> % cat game.rpm
0.1.0%
```
<img width="448" alt="game-proj" src="https://user-images.githubusercontent.com/898523/27999047-eab939da-64cc-11e7-8cb4-cd1403078580.png">

_Also, could you please show me the Content folder in your build engine folder, there might be something missing (there should be a build...Release/Content/basic/Content folder._

Sure, here is a screenshot with as many folders as I could open and still take the photo.
<img width="222" alt="content-folder-engine" src="https://user-images.githubusercontent.com/898523/27999089-7729634a-64cd-11e7-8e1e-0a851e9f22f4.png">
Since I couldn't open all the folders (and still take a screenshot) here is a visual from the `tree` command:
```sh
[RPG-Paper-Maker/build-Engine-Desktop_Qt_5_9_1_clang_64bit-Release/Content]
-> % tree
.
├── BR
│   └── Content
│       └── Pictures
│           ├── HUD
│           │   ├── Bars
│           │   │   ├── hpBar.png
│           │   │   ├── mpBar.png
│           │   │   └── spBar.png
│           │   └── Icons
│           │       ├── darkness.png
│           │       ├── fire.png
│           │       ├── grass.png
│           │       ├── light.png
│           │       ├── water.png
│           │       └── wind.png
│           └── Textures2D
│               ├── Autotiles
│               │   ├── grass.png
│               │   ├── ground.png
│               │   └── water.png
│               ├── Characters
│               │   ├── kate.png
│               │   ├── lucas.png
│               │   ├── lucas_act.png
│               │   └── template.png
│               ├── Reliefs
│               │   ├── desert.png
│               │   ├── grass.png
│               │   └── halloween.png
│               └── Tilesets
│                   ├── beach.png
│                   ├── halloween.png
│                   └── plains.png
├── basic
│   └── Content
│       └── Datas
│           ├── Scripts
│           │   ├── battler.js
│           │   ├── bitmap.js
│           │   ├── camera.js
│           │   ├── datas-armors.js
│           │   ├── datas-battle-system.js
│           │   ├── datas-classes.js
│           │   ├── datas-common-events.js
│           │   ├── datas-game.js
│           │   ├── datas-heroes.js
│           │   ├── datas-items.js
│           │   ├── datas-keyboard.js
│           │   ├── datas-monsters.js
│           │   ├── datas-pictures.js
│           │   ├── datas-skills.js
│           │   ├── datas-system.js
│           │   ├── datas-tilesets.js
│           │   ├── datas-troops.js
│           │   ├── datas-weapons.js
│           │   ├── desktop
│           │   │   └── includes.js
│           │   ├── event-command-2.js
│           │   ├── event-command.js
│           │   ├── game-item.js
│           │   ├── game-player.js
│           │   ├── game-skill.js
│           │   ├── game-stack.js
│           │   ├── game.js
│           │   ├── graphic-equip-stats.js
│           │   ├── graphic-equip.js
│           │   ├── graphic-item.js
│           │   ├── graphic-player-description.js
│           │   ├── graphic-player.js
│           │   ├── graphic-skill.js
│           │   ├── graphic-text.js
│           │   ├── main.js
│           │   ├── map-object.js
│           │   ├── map-portion.js
│           │   ├── reaction-interpreter.js
│           │   ├── scene-battle-0.js
│           │   ├── scene-battle-1.js
│           │   ├── scene-battle-2.js
│           │   ├── scene-battle-3.js
│           │   ├── scene-battle-4.js
│           │   ├── scene-battle.js
│           │   ├── scene-description-state.js
│           │   ├── scene-game.js
│           │   ├── scene-load-game.js
│           │   ├── scene-map.js
│           │   ├── scene-menu-equip.js
│           │   ├── scene-menu-inventory.js
│           │   ├── scene-menu-skills.js
│           │   ├── scene-menu.js
│           │   ├── scene-save-game.js
│           │   ├── scene-save-load-game.js
│           │   ├── scene-title-screen.js
│           │   ├── sprite.js
│           │   ├── system-armor.js
│           │   ├── system-class-skill.js
│           │   ├── system-class.js
│           │   ├── system-common-reaction.js
│           │   ├── system-currency.js
│           │   ├── system-element.js
│           │   ├── system-event.js
│           │   ├── system-hero.js
│           │   ├── system-item.js
│           │   ├── system-keyboard.js
│           │   ├── system-monster.js
│           │   ├── system-object-event.js
│           │   ├── system-object-reaction.js
│           │   ├── system-object-state.js
│           │   ├── system-object.js
│           │   ├── system-parameter.js
│           │   ├── system-picture.js
│           │   ├── system-skill.js
│           │   ├── system-statistic-progression.js
│           │   ├── system-statistic.js
│           │   ├── system-tileset.js
│           │   ├── system-troop.js
│           │   ├── system-value.js
│           │   ├── system-weapon-armor-kind.js
│           │   ├── system-weapon.js
│           │   ├── utilities.js
│           │   ├── wanok.js
│           │   ├── window-box.js
│           │   ├── window-choices.js
│           │   └── window-tabs.js
│           └── settings.json
├── linux
│   └── Game
├── web
│   ├── index.js
│   ├── index.php
│   ├── three.js
│   └── utilities.js
└── win32
    ├── Game.exe
    ├── Qt5Core.dll
    ├── Qt5Gui.dll
    ├── Qt5Network.dll
    ├── Qt5Qml.dll
    ├── Qt5Quick.dll
    ├── Qt5Svg.dll
    ├── Qt5Widgets.dll
    ├── QtCanvas3D
    │   ├── plugins.qmltypes
    │   ├── qmldir
    │   └── qtcanvas3d.dll
    ├── QtQuick
    │   ├── Dialogs
    │   │   ├── dialogplugin.dll
    │   │   └── qmldir
    │   └── Window.2
    │       ├── plugins.qmltypes
    │       ├── qmldir
    │       └── windowplugin.dll
    ├── QtQuick.2
    │   ├── plugins.qmltypes
    │   ├── qmldir
    │   └── qtquick2plugin.dll
    ├── libgcc_s_dw2-1.dll
    ├── libstdc++-6.dll
    ├── libwinpthread-1.dll
    └── platforms
        ├── qminimal.dll
        ├── qoffscreen.dll
        └── qwindows.dll

25 directories, 138 files
```

**Comment by Wano-k** [comment]
OK I've updated it in my last commit, could you pull it and retry please?

Retry also for the Game application and tell me what's displayed in the console output (and use the tree command to show me the Content folder of the Game too).

**Comment by afaur** [comment]
Okay, pulling it now.  Should be able to give you an update in a moment.

**Comment by afaur** [comment]
Great job with the error message! I think this really clarifies what is happening...
<img width="422" alt="debug-message" src="https://user-images.githubusercontent.com/898523/28000139-ae9677e0-64d8-11e7-9930-26c436a8db66.png">

I think since `mac osx` uses the `.app` format to encapsulate the actual binary inside of a containing folder structure, that the path is being resolved relative to that folder.

I went into the build folder and ran `tree` again (this time I ignored *.o|*.h|*.cpp to reduce the noise) and noticed that the `Content/data/Content` folder is in the root of the build directory, and not inside the `.app` container where the actual binary is executed from.

```sh
[CPP/RPG-Paper-Maker/build-Engine-Desktop_Qt_5_9_1_clang_64bit-Debug]
-> % tree -I "*.o|*.h|*.cpp"
.
├── Content
│   ├── BR
│   │   └── Content
│   │       └── Pictures
│   │           ├── HUD
│   │           │   ├── Bars
│   │           │   │   ├── hpBar.png
│   │           │   │   ├── mpBar.png
│   │           │   │   └── spBar.png
│   │           │   └── Icons
│   │           │       ├── darkness.png
│   │           │       ├── fire.png
│   │           │       ├── grass.png
│   │           │       ├── light.png
│   │           │       ├── water.png
│   │           │       └── wind.png
│   │           └── Textures2D
│   │               ├── Autotiles
│   │               │   ├── grass.png
│   │               │   ├── ground.png
│   │               │   └── water.png
│   │               ├── Characters
│   │               │   ├── kate.png
│   │               │   ├── lucas.png
│   │               │   ├── lucas_act.png
│   │               │   └── template.png
│   │               ├── Reliefs
│   │               │   ├── desert.png
│   │               │   ├── grass.png
│   │               │   └── halloween.png
│   │               └── Tilesets
│   │                   ├── beach.png
│   │                   ├── halloween.png
│   │                   └── plains.png
│   ├── basic
│   │   └── Content
│   │       └── Datas
│   │           ├── Scripts
│   │           │   ├── battler.js
│   │           │   ├── bitmap.js
│   │           │   ├── camera.js
│   │           │   ├── datas-armors.js
│   │           │   ├── datas-battle-system.js
│   │           │   ├── datas-classes.js
│   │           │   ├── datas-common-events.js
│   │           │   ├── datas-game.js
│   │           │   ├── datas-heroes.js
│   │           │   ├── datas-items.js
│   │           │   ├── datas-keyboard.js
│   │           │   ├── datas-monsters.js
│   │           │   ├── datas-pictures.js
│   │           │   ├── datas-skills.js
│   │           │   ├── datas-system.js
│   │           │   ├── datas-tilesets.js
│   │           │   ├── datas-troops.js
│   │           │   ├── datas-weapons.js
│   │           │   ├── desktop
│   │           │   │   └── includes.js
│   │           │   ├── event-command-2.js
│   │           │   ├── event-command.js
│   │           │   ├── game-item.js
│   │           │   ├── game-player.js
│   │           │   ├── game-skill.js
│   │           │   ├── game-stack.js
│   │           │   ├── game.js
│   │           │   ├── graphic-equip-stats.js
│   │           │   ├── graphic-equip.js
│   │           │   ├── graphic-item.js
│   │           │   ├── graphic-player-description.js
│   │           │   ├── graphic-player.js
│   │           │   ├── graphic-skill.js
│   │           │   ├── graphic-text.js
│   │           │   ├── main.js
│   │           │   ├── map-object.js
│   │           │   ├── map-portion.js
│   │           │   ├── reaction-interpreter.js
│   │           │   ├── scene-battle-0.js
│   │           │   ├── scene-battle-1.js
│   │           │   ├── scene-battle-2.js
│   │           │   ├── scene-battle-3.js
│   │           │   ├── scene-battle-4.js
│   │           │   ├── scene-battle.js
│   │           │   ├── scene-description-state.js
│   │           │   ├── scene-game.js
│   │           │   ├── scene-load-game.js
│   │           │   ├── scene-map.js
│   │           │   ├── scene-menu-equip.js
│   │           │   ├── scene-menu-inventory.js
│   │           │   ├── scene-menu-skills.js
│   │           │   ├── scene-menu.js
│   │           │   ├── scene-save-game.js
│   │           │   ├── scene-save-load-game.js
│   │           │   ├── scene-title-screen.js
│   │           │   ├── sprite.js
│   │           │   ├── system-armor.js
│   │           │   ├── system-class-skill.js
│   │           │   ├── system-class.js
│   │           │   ├── system-common-reaction.js
│   │           │   ├── system-currency.js
│   │           │   ├── system-element.js
│   │           │   ├── system-event.js
│   │           │   ├── system-hero.js
│   │           │   ├── system-item.js
│   │           │   ├── system-keyboard.js
│   │           │   ├── system-monster.js
│   │           │   ├── system-object-event.js
│   │           │   ├── system-object-reaction.js
│   │           │   ├── system-object-state.js
│   │           │   ├── system-object.js
│   │           │   ├── system-parameter.js
│   │           │   ├── system-picture.js
│   │           │   ├── system-skill.js
│   │           │   ├── system-statistic-progression.js
│   │           │   ├── system-statistic.js
│   │           │   ├── system-tileset.js
│   │           │   ├── system-troop.js
│   │           │   ├── system-value.js
│   │           │   ├── system-weapon-armor-kind.js
│   │           │   ├── system-weapon.js
│   │           │   ├── utilities.js
│   │           │   ├── wanok.js
│   │           │   ├── window-box.js
│   │           │   ├── window-choices.js
│   │           │   └── window-tabs.js
│   │           └── settings.json
│   ├── linux
│   │   └── Game
│   ├── osx
│   │   └── fakeApp
│   ├── web
│   │   ├── index.js
│   │   ├── index.php
│   │   ├── three.js
│   │   └── utilities.js
│   └── win32
│       ├── Game.exe
│       ├── Qt5Core.dll
│       ├── Qt5Gui.dll
│       ├── Qt5Network.dll
│       ├── Qt5Qml.dll
│       ├── Qt5Quick.dll
│       ├── Qt5Svg.dll
│       ├── Qt5Widgets.dll
│       ├── QtCanvas3D
│       │   ├── plugins.qmltypes
│       │   ├── qmldir
│       │   └── qtcanvas3d.dll
│       ├── QtQuick
│       │   ├── Dialogs
│       │   │   ├── dialogplugin.dll
│       │   │   └── qmldir
│       │   └── Window.2
│       │       ├── plugins.qmltypes
│       │       ├── qmldir
│       │       └── windowplugin.dll
│       ├── QtQuick.2
│       │   ├── plugins.qmltypes
│       │   ├── qmldir
│       │   └── qtquick2plugin.dll
│       ├── libgcc_s_dw2-1.dll
│       ├── libstdc++-6.dll
│       ├── libwinpthread-1.dll
│       └── platforms
│           ├── qminimal.dll
│           ├── qoffscreen.dll
│           └── qwindows.dll
├── Engine.app
│   └── Contents
│       ├── Info.plist
│       ├── MacOS
│       │   └── Engine
│       ├── PkgInfo
│       └── Resources
│           └── empty.lproj
└── Makefile

31 directories, 144 files
```

Let me know if this sounds accurate, but if not I can attempt some other things based on your suggestions.

**Comment by Wano-k** [comment]
Nice, I pushed a correction to have the right directory path. That might by the same issue for the Game app (I hope)! Is that OK now?

**Comment by afaur** [comment]
Sadly that didn't fix it. I spent a little time looking into this, and found this article (https://wiki.qt.io/Resource_files_in_OS_X_bundle). 

I wasn't sure how that would work so I looked a bit on stack overflow about adding folders, and found this (https://stackoverflow.com/questions/7631249/how-to-copy-update-resources-frameworks-or-plugins-to-the-mac-os-x-app-bundl#answers-header). 

I took that code and added it to the `Engine.pro` file at the bottom:
<img width="800" alt="add-content-to-bundle" src="https://user-images.githubusercontent.com/898523/28001523-0beb5a60-64e2-11e7-9057-dfb90e1ac1aa.png">

<img width="1440" alt="loaded" src="https://user-images.githubusercontent.com/898523/28001546-33ce6ac2-64e2-11e7-87c9-798bf6ecd831.png">

It works! Here is what the `tree` command shows now inside the `build` folder.

```sh
[CPP/RPG-Paper-Maker/build-Engine-Desktop_Qt_5_9_1_clang_64bit-Debug]
-> % tree -I "*.o|*.h|*.cpp"
.
├── Content
│   ├── BR
│   │   └── Content
│   │       └── Pictures
│   │           ├── HUD
│   │           │   ├── Bars
│   │           │   │   ├── hpBar.png
│   │           │   │   ├── mpBar.png
│   │           │   │   └── spBar.png
│   │           │   └── Icons
│   │           │       ├── darkness.png
│   │           │       ├── fire.png
│   │           │       ├── grass.png
│   │           │       ├── light.png
│   │           │       ├── water.png
│   │           │       └── wind.png
│   │           └── Textures2D
│   │               ├── Autotiles
│   │               │   ├── grass.png
│   │               │   ├── ground.png
│   │               │   └── water.png
│   │               ├── Characters
│   │               │   ├── kate.png
│   │               │   ├── lucas.png
│   │               │   ├── lucas_act.png
│   │               │   └── template.png
│   │               ├── Reliefs
│   │               │   ├── desert.png
│   │               │   ├── grass.png
│   │               │   └── halloween.png
│   │               └── Tilesets
│   │                   ├── beach.png
│   │                   ├── halloween.png
│   │                   └── plains.png
│   ├── basic
│   │   └── Content
│   │       └── Datas
│   │           ├── Scripts
│   │           │   ├── battler.js
│   │           │   ├── bitmap.js
│   │           │   ├── camera.js
│   │           │   ├── datas-armors.js
│   │           │   ├── datas-battle-system.js
│   │           │   ├── datas-classes.js
│   │           │   ├── datas-common-events.js
│   │           │   ├── datas-game.js
│   │           │   ├── datas-heroes.js
│   │           │   ├── datas-items.js
│   │           │   ├── datas-keyboard.js
│   │           │   ├── datas-monsters.js
│   │           │   ├── datas-pictures.js
│   │           │   ├── datas-skills.js
│   │           │   ├── datas-system.js
│   │           │   ├── datas-tilesets.js
│   │           │   ├── datas-troops.js
│   │           │   ├── datas-weapons.js
│   │           │   ├── desktop
│   │           │   │   └── includes.js
│   │           │   ├── event-command-2.js
│   │           │   ├── event-command.js
│   │           │   ├── game-item.js
│   │           │   ├── game-player.js
│   │           │   ├── game-skill.js
│   │           │   ├── game-stack.js
│   │           │   ├── game.js
│   │           │   ├── graphic-equip-stats.js
│   │           │   ├── graphic-equip.js
│   │           │   ├── graphic-item.js
│   │           │   ├── graphic-player-description.js
│   │           │   ├── graphic-player.js
│   │           │   ├── graphic-skill.js
│   │           │   ├── graphic-text.js
│   │           │   ├── main.js
│   │           │   ├── map-object.js
│   │           │   ├── map-portion.js
│   │           │   ├── reaction-interpreter.js
│   │           │   ├── scene-battle-0.js
│   │           │   ├── scene-battle-1.js
│   │           │   ├── scene-battle-2.js
│   │           │   ├── scene-battle-3.js
│   │           │   ├── scene-battle-4.js
│   │           │   ├── scene-battle.js
│   │           │   ├── scene-description-state.js
│   │           │   ├── scene-game.js
│   │           │   ├── scene-load-game.js
│   │           │   ├── scene-map.js
│   │           │   ├── scene-menu-equip.js
│   │           │   ├── scene-menu-inventory.js
│   │           │   ├── scene-menu-skills.js
│   │           │   ├── scene-menu.js
│   │           │   ├── scene-save-game.js
│   │           │   ├── scene-save-load-game.js
│   │           │   ├── scene-title-screen.js
│   │           │   ├── sprite.js
│   │           │   ├── system-armor.js
│   │           │   ├── system-class-skill.js
│   │           │   ├── system-class.js
│   │           │   ├── system-common-reaction.js
│   │           │   ├── system-currency.js
│   │           │   ├── system-element.js
│   │           │   ├── system-event.js
│   │           │   ├── system-hero.js
│   │           │   ├── system-item.js
│   │           │   ├── system-keyboard.js
│   │           │   ├── system-monster.js
│   │           │   ├── system-object-event.js
│   │           │   ├── system-object-reaction.js
│   │           │   ├── system-object-state.js
│   │           │   ├── system-object.js
│   │           │   ├── system-parameter.js
│   │           │   ├── system-picture.js
│   │           │   ├── system-skill.js
│   │           │   ├── system-statistic-progression.js
│   │           │   ├── system-statistic.js
│   │           │   ├── system-tileset.js
│   │           │   ├── system-troop.js
│   │           │   ├── system-value.js
│   │           │   ├── system-weapon-armor-kind.js
│   │           │   ├── system-weapon.js
│   │           │   ├── utilities.js
│   │           │   ├── wanok.js
│   │           │   ├── window-box.js
│   │           │   ├── window-choices.js
│   │           │   └── window-tabs.js
│   │           └── settings.json
│   ├── linux
│   │   └── Game
│   ├── osx
│   │   └── fakeApp
│   ├── web
│   │   ├── index.js
│   │   ├── index.php
│   │   ├── three.js
│   │   └── utilities.js
│   └── win32
│       ├── Game.exe
│       ├── Qt5Core.dll
│       ├── Qt5Gui.dll
│       ├── Qt5Network.dll
│       ├── Qt5Qml.dll
│       ├── Qt5Quick.dll
│       ├── Qt5Svg.dll
│       ├── Qt5Widgets.dll
│       ├── QtCanvas3D
│       │   ├── plugins.qmltypes
│       │   ├── qmldir
│       │   └── qtcanvas3d.dll
│       ├── QtQuick
│       │   ├── Dialogs
│       │   │   ├── dialogplugin.dll
│       │   │   └── qmldir
│       │   └── Window.2
│       │       ├── plugins.qmltypes
│       │       ├── qmldir
│       │       └── windowplugin.dll
│       ├── QtQuick.2
│       │   ├── plugins.qmltypes
│       │   ├── qmldir
│       │   └── qtquick2plugin.dll
│       ├── libgcc_s_dw2-1.dll
│       ├── libstdc++-6.dll
│       ├── libwinpthread-1.dll
│       └── platforms
│           ├── qminimal.dll
│           ├── qoffscreen.dll
│           └── qwindows.dll
├── Engine.app
│   └── Contents
│       ├── Info.plist
│       ├── MacOS
│       │   ├── Content
│       │   │   ├── BR
│       │   │   │   └── Content
│       │   │   │       └── Pictures
│       │   │   │           ├── HUD
│       │   │   │           │   ├── Bars
│       │   │   │           │   │   ├── hpBar.png
│       │   │   │           │   │   ├── mpBar.png
│       │   │   │           │   │   └── spBar.png
│       │   │   │           │   └── Icons
│       │   │   │           │       ├── darkness.png
│       │   │   │           │       ├── fire.png
│       │   │   │           │       ├── grass.png
│       │   │   │           │       ├── light.png
│       │   │   │           │       ├── water.png
│       │   │   │           │       └── wind.png
│       │   │   │           └── Textures2D
│       │   │   │               ├── Autotiles
│       │   │   │               │   ├── grass.png
│       │   │   │               │   ├── ground.png
│       │   │   │               │   └── water.png
│       │   │   │               ├── Characters
│       │   │   │               │   ├── kate.png
│       │   │   │               │   ├── lucas.png
│       │   │   │               │   ├── lucas_act.png
│       │   │   │               │   └── template.png
│       │   │   │               ├── Reliefs
│       │   │   │               │   ├── desert.png
│       │   │   │               │   ├── grass.png
│       │   │   │               │   └── halloween.png
│       │   │   │               └── Tilesets
│       │   │   │                   ├── beach.png
│       │   │   │                   ├── halloween.png
│       │   │   │                   └── plains.png
│       │   │   ├── basic
│       │   │   │   └── Content
│       │   │   │       └── Datas
│       │   │   │           └── settings.json
│       │   │   ├── engineSettings.json
│       │   │   ├── linux
│       │   │   │   └── Game
│       │   │   ├── osx
│       │   │   │   └── fakeApp
│       │   │   ├── web
│       │   │   │   ├── index.js
│       │   │   │   ├── index.php
│       │   │   │   ├── three.js
│       │   │   │   └── utilities.js
│       │   │   └── win32
│       │   │       ├── Game.exe
│       │   │       ├── Qt5Core.dll
│       │   │       ├── Qt5Gui.dll
│       │   │       ├── Qt5Network.dll
│       │   │       ├── Qt5Qml.dll
│       │   │       ├── Qt5Quick.dll
│       │   │       ├── Qt5Svg.dll
│       │   │       ├── Qt5Widgets.dll
│       │   │       ├── QtCanvas3D
│       │   │       │   ├── plugins.qmltypes
│       │   │       │   ├── qmldir
│       │   │       │   └── qtcanvas3d.dll
│       │   │       ├── QtQuick
│       │   │       │   ├── Dialogs
│       │   │       │   │   ├── dialogplugin.dll
│       │   │       │   │   └── qmldir
│       │   │       │   └── Window.2
│       │   │       │       ├── plugins.qmltypes
│       │   │       │       ├── qmldir
│       │   │       │       └── windowplugin.dll
│       │   │       ├── QtQuick.2
│       │   │       │   ├── plugins.qmltypes
│       │   │       │   ├── qmldir
│       │   │       │   └── qtquick2plugin.dll
│       │   │       ├── libgcc_s_dw2-1.dll
│       │   │       ├── libstdc++-6.dll
│       │   │       ├── libwinpthread-1.dll
│       │   │       └── platforms
│       │   │           ├── qminimal.dll
│       │   │           ├── qoffscreen.dll
│       │   │           └── qwindows.dll
│       │   └── Engine
│       ├── PkgInfo
│       └── Resources
│           └── empty.lproj
└── Makefile

56 directories, 199 files
```

Since the `.app` is what will be released, and the `Content` folder is a requirement for the `Engine` to create new projects it should probably be included in the `.app` bundle which is what that addition to the `.pro` file seems to do. 

The only thing I would change about this is to tell Qt to place the `Content` folder inside of `Contents/Resources` instead of `Contents/MacOS`, but if you do that I don't think the logic your using to copy the files over would work for mac.

If you want some help working on this I am interested in helping out. I have a limited understanding of c++ and have not worked with Qt much before, but I could give it a try.

**Comment by Wano-k** [comment]
Nice work! That's strange that all the resources are put inside the app (I'm not comfortable with mac so I don't know if it's a common way to do). If the user wants to put their own textures, will it be possible without difficulties? Also we should not proceed on the standard outside copy if it's already on the bundle. That's also strange that it didn't work. You had the same error message? (same path?)

If you look at `main.cpp` l.39:

```
QDir bin(qApp->applicationFilePath());
#if defined(Q_WS_MAC)
    bin.cdUp();
    bin.cdUp();
    bin.cdUp();
#endif
QDir::setCurrent(bin.absolutePath());
```

I suspect that you are not going inside the if. Try with this:

```
QDir bin(qApp->applicationDirPath());
#ifdef Q_OS_MAC
    bin.cdUp();
    bin.cdUp();
    bin.cdUp();
#endif
QDir::setCurrent(bin.absolutePath());
```

The `QDir::currentPath()` should return a path to the Content folder.

Thanks again, you are really helpful!

**Comment by afaur** [comment]
_Nice work! That's strange that all the resources are put inside the app (I'm not comfortable with mac so I don't know if it's a common way to do)._

It would be most common to do so, and have the first run install those assets to another folder on the system.

_If the user wants to put their own textures, will it be possible without difficulties?_

I think if the intent is for others to replace the contents then on a mac those contents could be installed in the current users application support directory (`~/Library/Application Support/Rpg Paper Maker Editor`).

I noticed you currently use `~/Documents/RPG Paper Maker Games` as a default for storing the games, and copying the assets. (https://github.com/Wano-k/RPG-Paper-Maker/blob/develop/Engine/Singletons/wanok.cpp#L77-L80)

Maybe there is a way on `mac` for `qt` to give you the path to the `~/Library/Application Support` directory. An example of an application that uses this directory is `steam` which uses it to store all their games, and resources.

_Also we should not proceed on the standard outside copy if it's already on the bundle._

I think initially all the `Content` assets (for the mac build) should be kept inside the `.app` only.

_That's also strange that it didn't work. You had the same error message? (same path?)_

Yes, same error message. I just pulled down your new changes, and it works correctly now. 👍 

I think how you have it currently working should be perfectly fine. I could imagine in the future changing this, but I think it is probably a low priority issue.

If there is anything else I can help out with let me know. I saw the excel spreadsheet that was linked to in the `README.md`. 

It might be helpful to create a new `projects` board to help manage priorities and issues:

<img width="650" alt="projects-board" src="https://user-images.githubusercontent.com/898523/28027187-0bca8f90-654d-11e7-9174-d48eb526007c.png">


It creates a project tracker that helps you use github to manage what things are being worked on.


<img width="670" alt="create-tracker" src="https://user-images.githubusercontent.com/898523/28027425-e10e2fae-654d-11e7-98ff-c3656edaa741.png">

After creating the project you are provided an interface where you can create `columns` and add `cards` to them.


<img width="860" alt="tracker-ui" src="https://user-images.githubusercontent.com/898523/28027482-0ad9543a-654e-11e7-8ea6-542fafc9168e.png">


One common way I like to set this up is to track progress of what is being worked on.


<img width="995" alt="tracker-progress" src="https://user-images.githubusercontent.com/898523/28027522-309b6bf4-654e-11e7-9bc1-4e49c7e67b74.png">


Another column that could exist would be `Review` where issues could be moved before `done`. This location could be where a PR is in progress, or discussion is happening before completion.

You add `cards` to each `column` (initially for this setup, each card would be placed in `todo`) A card can either be pulled in from your `issues` board, or created manually.


<img width="360" alt="add-cards" src="https://user-images.githubusercontent.com/898523/28027639-9e24fa50-654e-11e7-87d5-a03e8faf8156.png">

**Comment by Wano-k** [comment]
> Maybe there is a way on mac for qt to give you the path to the ~/Library/Application Support directory. 

Yep, looks like it is `QStandardPaths::RuntimeLocation`. I will update it for mac users!

> I think how you have it currently working should be perfectly fine. I could imagine in the future changing this, but I think it is probably a low priority issue.

Not sure, you mean the Content outside or inside the app?

> If there is anything else I can help out with let me know

All is in the first post. I will update the Game folder this evening and you could tell me if you always have an error message. If the title screen is displayed all is OK (don't try a new game, the pictures here doesn't have a correct path).

Thanks for the project guide, I never used it and didn't know how it was used for! I'll update it.

**Comment by afaur** [comment]
> Maybe there is a way on mac for qt to give you the path to the ~/Library/Application Support directory.

- > Yep, looks like it is QStandardPaths::RuntimeLocation. I will update it for mac users!

- I think just keeping it in mind is enough at the current time. You won't need to use it in your code until you choose to refactor the code that makes it the primary place to store assets after the application gets installed for the first time.  I can help with this, but it might be good to open an issue to discuss the changes required for this approach.

> I think how you have it currently working should be perfectly fine. I could imagine in the future changing this, but I think it is probably a low priority issue.

- > Not sure, you mean the Content outside or inside the app?

- I think keeping it outside for now is perfectly fine.

> All is in the first post. I will update the Game folder this evening and you could tell me if you always have an error message. 

Okay, sounds good.  I created (https://github.com/Wano-k/RPG-Paper-Maker/issues/2) which eventually could automate the creation of the `linux`, `mac`, and `windows` release builds and publishing them onto github automatically when you push up a `tag` to your repository.  At the moment I am trying to get it to indicate if anyone pushes changes that cause the `build` to fail and indicate that on github.

**Comment by afaur** [comment]
Instead of keeping `releases` for each operating system inside of `Engine/Content/OS_NAME` github has a place for storing and tracking these outside of your repositories branches git history:

<img width="985" alt="store-releases" src="https://user-images.githubusercontent.com/898523/28032686-4357e076-6560-11e7-87e8-0c25c5e9ced9.png">

Here is a guide on how this works doing it manually
(https://help.github.com/articles/creating-releases/)

If (https://github.com/Wano-k/RPG-Paper-Maker/issues/2) is completed this process would be automated when you push a `tag` to your repository.

**Comment by Wano-k** [comment]
The `Engine/Content/OS_NAME` does not contain any release, it's all the binaries files that are copied when creating a new project (depending on the OS). So, I think this should stay here. However, I have a `Downloads` folder in the `master` branch only for the releases, I'm putting it in the git release!

**Comment by afaur** [comment]
I did not know`Engine` required release builds of `Game` for each operating system. If I understand this correctly I could imagine breaking this project into two repositories. 

If right now you pushed a `tag` to `RPG-Paper-Maker` it would cause releases of `Engine` and `Game` to be produced and added to the `releases` section of the repository (it should at least if everything worked). 

The problem with this is that your release of `Engine` should include the most recent release of `Game`. (this is a problem because the generation of the binaries of both occur at the exact same time and therefore you cannot fetch the latest release of `Game` from the github api and include it in your releases `.zip/.tar.gz/.pkg` of `Engine`.)

**Comment by afaur** [comment]
This may over complicate things right now, but it may be better to spend effort on programming instead of making, and managing binaries manually.

If everything is set up a particular way I believe a new alpha/beta/rc release for every platform could be built multiple times a day without much thought or interaction by the developer.

**Comment by afaur** [comment]
I am actually unsure if when a tag is pushed if the artifacts from a prior PR at that same SHA could exist.  If that is the case then maybe separating would not be as much of a benefit. I think I will investigate this more and see if the current repository setup will work just as well.

**Comment by Wano-k** [comment]
Good news Afaur, I'll get an old macbook soon so I'll be able to deploy at least manually on this platform. However I guess that it will not be an easy task as a fresh new mac user. :D

See you in gitter if I have any request.
